function CodeDefine() { 
this.def = new Array();
this.def["runModel"] = {file: "ert_main_c.html",line:68,type:"var"};
this.def["stopSem"] = {file: "ert_main_c.html",line:69,type:"var"};
this.def["baserateTaskSem"] = {file: "ert_main_c.html",line:70,type:"var"};
this.def["schedulerThread"] = {file: "ert_main_c.html",line:77,type:"var"};
this.def["baseRateThread"] = {file: "ert_main_c.html",line:78,type:"var"};
this.def["threadJoinStatus"] = {file: "ert_main_c.html",line:79,type:"var"};
this.def["terminatingmodel"] = {file: "ert_main_c.html",line:80,type:"var"};
this.def["baseRateTask"] = {file: "ert_main_c.html",line:81,type:"fcn"};
this.def["exitFcn"] = {file: "ert_main_c.html",line:98,type:"fcn"};
this.def["terminateTask"] = {file: "ert_main_c.html",line:104,type:"fcn"};
this.def["px4_simulink_app_main"] = {file: "ert_main_c.html",line:119,type:"fcn"};
this.def["ModeSwitch_HIL_B"] = {file: "ModeSwitch_HIL_c.html",line:24,type:"var"};
this.def["ModeSwitch_HIL_DW"] = {file: "ModeSwitch_HIL_c.html",line:27,type:"var"};
this.def["ModeSwitch_HIL.c:ModeSwitch_HIL_M_"] = {file: "ModeSwitch_HIL_c.html",line:30,type:"var"};
this.def["ModeSwitch_HIL_M"] = {file: "ModeSwitch_HIL_c.html",line:31,type:"var"};
this.def["ModeSwitch_HIL.c:rate_scheduler"] = {file: "ModeSwitch_HIL_c.html",line:39,type:"fcn"};
this.def["ModeSwitch_HIL_deadzone1"] = {file: "ModeSwitch_HIL_c.html",line:61,type:"fcn"};
this.def["rt_atan2f_snf"] = {file: "ModeSwitch_HIL_c.html",line:104,type:"fcn"};
this.def["ModeSwitch_HIL_step"] = {file: "ModeSwitch_HIL_c.html",line:141,type:"fcn"};
this.def["ModeSwitch_HIL_initialize"] = {file: "ModeSwitch_HIL_c.html",line:1683,type:"fcn"};
this.def["ModeSwitch_HIL_terminate"] = {file: "ModeSwitch_HIL_c.html",line:1908,type:"fcn"};
this.def["pollfd_t"] = {file: "ModeSwitch_HIL_h.html",line:67,type:"type"};
this.def["led_control_s_t"] = {file: "ModeSwitch_HIL_h.html",line:68,type:"type"};
this.def["actuator_outputs_s_t"] = {file: "ModeSwitch_HIL_h.html",line:69,type:"type"};
this.def["pollfd_t"] = {file: "ModeSwitch_HIL_h.html",line:70,type:"type"};
this.def["vehicle_local_position_SL"] = {file: "ModeSwitch_HIL_h.html",line:71,type:"type"};
this.def["B_deadzone1_ModeSwitch_HIL_T"] = {file: "ModeSwitch_HIL_h.html",line:76,type:"type"};
this.def["B_ModeSwitch_HIL_T"] = {file: "ModeSwitch_HIL_h.html",line:123,type:"type"};
this.def["DW_ModeSwitch_HIL_T"] = {file: "ModeSwitch_HIL_h.html",line:165,type:"type"};
this.def["RGBLED_MODE_ENUM"] = {file: "ModeSwitch_HIL_types_h.html",line:37,type:"type"};
this.def["RGBLED_COLOR_ENUM"] = {file: "ModeSwitch_HIL_types_h.html",line:54,type:"type"};
this.def["RT_MODEL_ModeSwitch_HIL_T"] = {file: "ModeSwitch_HIL_types_h.html",line:59,type:"type"};
this.def["rtGetInf"] = {file: "rtGetInf_c.html",line:31,type:"fcn"};
this.def["rtGetInfF"] = {file: "rtGetInf_c.html",line:55,type:"fcn"};
this.def["rtGetMinusInf"] = {file: "rtGetInf_c.html",line:66,type:"fcn"};
this.def["rtGetMinusInfF"] = {file: "rtGetInf_c.html",line:90,type:"fcn"};
this.def["rtGetNaN"] = {file: "rtGetNaN_c.html",line:31,type:"fcn"};
this.def["rtGetNaNF"] = {file: "rtGetNaN_c.html",line:55,type:"fcn"};
this.def["rtInf"] = {file: "rt_nonfinite_c.html",line:30,type:"var"};
this.def["rtMinusInf"] = {file: "rt_nonfinite_c.html",line:31,type:"var"};
this.def["rtNaN"] = {file: "rt_nonfinite_c.html",line:32,type:"var"};
this.def["rtInfF"] = {file: "rt_nonfinite_c.html",line:33,type:"var"};
this.def["rtMinusInfF"] = {file: "rt_nonfinite_c.html",line:34,type:"var"};
this.def["rtNaNF"] = {file: "rt_nonfinite_c.html",line:35,type:"var"};
this.def["rt_InitInfAndNaN"] = {file: "rt_nonfinite_c.html",line:41,type:"fcn"};
this.def["rtIsInf"] = {file: "rt_nonfinite_c.html",line:53,type:"fcn"};
this.def["rtIsInfF"] = {file: "rt_nonfinite_c.html",line:59,type:"fcn"};
this.def["rtIsNaN"] = {file: "rt_nonfinite_c.html",line:65,type:"fcn"};
this.def["rtIsNaNF"] = {file: "rt_nonfinite_c.html",line:87,type:"fcn"};
this.def["BigEndianIEEEDouble"] = {file: "rt_nonfinite_h.html",line:41,type:"type"};
this.def["LittleEndianIEEEDouble"] = {file: "rt_nonfinite_h.html",line:48,type:"type"};
this.def["IEEESingle"] = {file: "rt_nonfinite_h.html",line:55,type:"type"};
this.def["int8_T"] = {file: "rtwtypes_h.html",line:51,type:"type"};
this.def["uint8_T"] = {file: "rtwtypes_h.html",line:52,type:"type"};
this.def["int16_T"] = {file: "rtwtypes_h.html",line:53,type:"type"};
this.def["uint16_T"] = {file: "rtwtypes_h.html",line:54,type:"type"};
this.def["int32_T"] = {file: "rtwtypes_h.html",line:55,type:"type"};
this.def["uint32_T"] = {file: "rtwtypes_h.html",line:56,type:"type"};
this.def["real32_T"] = {file: "rtwtypes_h.html",line:57,type:"type"};
this.def["real64_T"] = {file: "rtwtypes_h.html",line:58,type:"type"};
this.def["real_T"] = {file: "rtwtypes_h.html",line:64,type:"type"};
this.def["time_T"] = {file: "rtwtypes_h.html",line:65,type:"type"};
this.def["boolean_T"] = {file: "rtwtypes_h.html",line:66,type:"type"};
this.def["int_T"] = {file: "rtwtypes_h.html",line:67,type:"type"};
this.def["uint_T"] = {file: "rtwtypes_h.html",line:68,type:"type"};
this.def["ulong_T"] = {file: "rtwtypes_h.html",line:69,type:"type"};
this.def["char_T"] = {file: "rtwtypes_h.html",line:70,type:"type"};
this.def["uchar_T"] = {file: "rtwtypes_h.html",line:71,type:"type"};
this.def["byte_T"] = {file: "rtwtypes_h.html",line:72,type:"type"};
this.def["creal32_T"] = {file: "rtwtypes_h.html",line:82,type:"type"};
this.def["creal64_T"] = {file: "rtwtypes_h.html",line:87,type:"type"};
this.def["creal_T"] = {file: "rtwtypes_h.html",line:92,type:"type"};
this.def["cint8_T"] = {file: "rtwtypes_h.html",line:99,type:"type"};
this.def["cuint8_T"] = {file: "rtwtypes_h.html",line:106,type:"type"};
this.def["cint16_T"] = {file: "rtwtypes_h.html",line:113,type:"type"};
this.def["cuint16_T"] = {file: "rtwtypes_h.html",line:120,type:"type"};
this.def["cint32_T"] = {file: "rtwtypes_h.html",line:127,type:"type"};
this.def["cuint32_T"] = {file: "rtwtypes_h.html",line:134,type:"type"};
this.def["pointer_T"] = {file: "rtwtypes_h.html",line:152,type:"type"};
this.def["PX4_Simulink_Task_Sem"] = {file: "PX4_TaskControl_c.html",line:38,type:"var"};
this.def["PX4_Simulink_Task_Callback"] = {file: "PX4_TaskControl_c.html",line:44,type:"fcn"};
this.def["px4_app_usage"] = {file: "PX4_TaskControl_c.html",line:107,type:"fcn"};
this.def["attr"] = {file: "nuttxinitialize_c.html",line:26,type:"var"};
this.def["nuttxinitialize.c:g_info"] = {file: "nuttxinitialize_c.html",line:27,type:"var"};
this.def["g_sp"] = {file: "nuttxinitialize_c.html",line:28,type:"var"};
this.def["g_baseRateLife"] = {file: "nuttxinitialize_c.html",line:29,type:"var"};
this.def["BaseRate_HRT"] = {file: "nuttxinitialize_c.html",line:35,type:"var"};
this.def["EXT_sig_info"] = {file: "nuttxinitialize_c.html",line:45,type:"var"};
this.def["setTaskPeriod"] = {file: "nuttxinitialize_c.html",line:50,type:"fcn"};
this.def["baserate_sem_copy"] = {file: "nuttxinitialize_c.html",line:76,type:"var"};
this.def["print_sem_value"] = {file: "nuttxinitialize_c.html",line:77,type:"fcn"};
this.def["nuttxinitialize.c:Base_HRT_Callback"] = {file: "nuttxinitialize_c.html",line:82,type:"fcn"};
this.def["myWaitForThisEvent"] = {file: "nuttxinitialize_c.html",line:108,type:"fcn"};
this.def["myAddBlockForThisEvent"] = {file: "nuttxinitialize_c.html",line:118,type:"fcn"};
this.def["nuttxRTOSInit"] = {file: "nuttxinitialize_c.html",line:129,type:"fcn"};
}
CodeDefine.instance = new CodeDefine();
var testHarnessInfo = {OwnerFileName: "", HarnessOwner: "", HarnessName: "", IsTestHarness: "0"};
var relPathToBuildDir = "../ert_main.c";
var fileSep = "\\";
var isPC = true;
function Html2SrcLink() {
	this.html2SrcPath = new Array;
	this.html2Root = new Array;
	this.html2SrcPath["ert_main_c.html"] = "../ert_main.c";
	this.html2Root["ert_main_c.html"] = "ert_main_c.html";
	this.html2SrcPath["ModeSwitch_HIL_c.html"] = "../ModeSwitch_HIL.c";
	this.html2Root["ModeSwitch_HIL_c.html"] = "ModeSwitch_HIL_c.html";
	this.html2SrcPath["ModeSwitch_HIL_h.html"] = "../ModeSwitch_HIL.h";
	this.html2Root["ModeSwitch_HIL_h.html"] = "ModeSwitch_HIL_h.html";
	this.html2SrcPath["ModeSwitch_HIL_private_h.html"] = "../ModeSwitch_HIL_private.h";
	this.html2Root["ModeSwitch_HIL_private_h.html"] = "ModeSwitch_HIL_private_h.html";
	this.html2SrcPath["ModeSwitch_HIL_types_h.html"] = "../ModeSwitch_HIL_types.h";
	this.html2Root["ModeSwitch_HIL_types_h.html"] = "ModeSwitch_HIL_types_h.html";
	this.html2SrcPath["rtGetInf_c.html"] = "../rtGetInf.c";
	this.html2Root["rtGetInf_c.html"] = "rtGetInf_c.html";
	this.html2SrcPath["rtGetInf_h.html"] = "../rtGetInf.h";
	this.html2Root["rtGetInf_h.html"] = "rtGetInf_h.html";
	this.html2SrcPath["rtGetNaN_c.html"] = "../rtGetNaN.c";
	this.html2Root["rtGetNaN_c.html"] = "rtGetNaN_c.html";
	this.html2SrcPath["rtGetNaN_h.html"] = "../rtGetNaN.h";
	this.html2Root["rtGetNaN_h.html"] = "rtGetNaN_h.html";
	this.html2SrcPath["rt_defines_h.html"] = "../rt_defines.h";
	this.html2Root["rt_defines_h.html"] = "rt_defines_h.html";
	this.html2SrcPath["rt_nonfinite_c.html"] = "../rt_nonfinite.c";
	this.html2Root["rt_nonfinite_c.html"] = "rt_nonfinite_c.html";
	this.html2SrcPath["rt_nonfinite_h.html"] = "../rt_nonfinite.h";
	this.html2Root["rt_nonfinite_h.html"] = "rt_nonfinite_h.html";
	this.html2SrcPath["rtwtypes_h.html"] = "../rtwtypes.h";
	this.html2Root["rtwtypes_h.html"] = "rtwtypes_h.html";
	this.html2SrcPath["rtmodel_h.html"] = "../rtmodel.h";
	this.html2Root["rtmodel_h.html"] = "rtmodel_h.html";
	this.html2SrcPath["MW_custom_RTOS_header_h.html"] = "../MW_custom_RTOS_header.h";
	this.html2Root["MW_custom_RTOS_header_h.html"] = "MW_custom_RTOS_header_h.html";
	this.html2SrcPath["MW_target_hardware_resources_h.html"] = "../MW_target_hardware_resources.h";
	this.html2Root["MW_target_hardware_resources_h.html"] = "MW_target_hardware_resources_h.html";
	this.html2SrcPath["PX4_TaskControl_c.html"] = "file:///C:/Users/guosh/Documents/MATLAB/Add-Ons/Toolboxes/PX4PSP/code/src/PX4_TaskControl.c";
	this.html2Root["PX4_TaskControl_c.html"] = "PX4_TaskControl_c.html";
	this.html2SrcPath["nuttxinitialize_c.html"] = "file:///C:/Users/guosh/Documents/MATLAB/Add-Ons/Toolboxes/PX4PSP/code/src/nuttxinitialize.c";
	this.html2Root["nuttxinitialize_c.html"] = "nuttxinitialize_c.html";
	this.getLink2Src = function (htmlFileName) {
		 if (this.html2SrcPath[htmlFileName])
			 return this.html2SrcPath[htmlFileName];
		 else
			 return null;
	}
	this.getLinkFromRoot = function (htmlFileName) {
		 if (this.html2Root[htmlFileName])
			 return this.html2Root[htmlFileName];
		 else
			 return null;
	}
}
Html2SrcLink.instance = new Html2SrcLink();
var fileList = [
"ert_main_c.html","ModeSwitch_HIL_c.html","ModeSwitch_HIL_h.html","ModeSwitch_HIL_private_h.html","ModeSwitch_HIL_types_h.html","rtGetInf_c.html","rtGetInf_h.html","rtGetNaN_c.html","rtGetNaN_h.html","rt_defines_h.html","rt_nonfinite_c.html","rt_nonfinite_h.html","rtwtypes_h.html","rtmodel_h.html","MW_custom_RTOS_header_h.html","MW_target_hardware_resources_h.html","PX4_TaskControl_c.html","nuttxinitialize_c.html"];
